name: PR metadata annotation

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    name: Annotates pull request with metadata
    steps:
      - name: Annotate PR
        uses: boydzweers/UI5-eocp-check@main
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          prNumber: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          pathToIndex: web/webapp/index.html
          failOnEOCP: true
