name: UI5 End of Cloud Provisioning Check

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check-ui5-eocp:
    runs-on: ubuntu-latest
    name: Checks the actual used version of UI5 against the EOCP versions
    steps:
      - name: Checks the actual used version of UI5 against the EOCP versions
        uses: boydzweers/UI5-eocp-check@main
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issueNumber: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          pathToIndex: web/webapp/index.html
          failOnEOCP: true
